{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "5785e774",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd \n",
    "import numpy as np\n",
    "\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import mean_squared_error"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9d45e258",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>price</th>\n",
       "      <th>area</th>\n",
       "      <th>bedrooms</th>\n",
       "      <th>bathrooms</th>\n",
       "      <th>stories</th>\n",
       "      <th>mainroad</th>\n",
       "      <th>guestroom</th>\n",
       "      <th>basement</th>\n",
       "      <th>hotwaterheating</th>\n",
       "      <th>airconditioning</th>\n",
       "      <th>parking</th>\n",
       "      <th>prefarea</th>\n",
       "      <th>furnishingstatus</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>13300000</td>\n",
       "      <td>7420</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "      <td>3</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>yes</td>\n",
       "      <td>2</td>\n",
       "      <td>yes</td>\n",
       "      <td>furnished</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>12250000</td>\n",
       "      <td>8960</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>yes</td>\n",
       "      <td>3</td>\n",
       "      <td>no</td>\n",
       "      <td>furnished</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>12250000</td>\n",
       "      <td>9960</td>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>2</td>\n",
       "      <td>yes</td>\n",
       "      <td>semi-furnished</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>12215000</td>\n",
       "      <td>7500</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>yes</td>\n",
       "      <td>3</td>\n",
       "      <td>yes</td>\n",
       "      <td>furnished</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>11410000</td>\n",
       "      <td>7420</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>yes</td>\n",
       "      <td>yes</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>yes</td>\n",
       "      <td>2</td>\n",
       "      <td>no</td>\n",
       "      <td>furnished</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \\\n",
       "0  13300000  7420         4          2        3      yes        no       no   \n",
       "1  12250000  8960         4          4        4      yes        no       no   \n",
       "2  12250000  9960         3          2        2      yes        no      yes   \n",
       "3  12215000  7500         4          2        2      yes        no      yes   \n",
       "4  11410000  7420         4          1        2      yes       yes      yes   \n",
       "\n",
       "  hotwaterheating airconditioning  parking prefarea furnishingstatus  \n",
       "0              no             yes        2      yes        furnished  \n",
       "1              no             yes        3       no        furnished  \n",
       "2              no              no        2      yes   semi-furnished  \n",
       "3              no             yes        3      yes        furnished  \n",
       "4              no             yes        2       no        furnished  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.read_csv(r\"C:\\Users\\SRINIDHI\\OneDrive\\Desktop\\FL-Sem6\\Housing.csv\")\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d1514379",
   "metadata": {},
   "outputs": [],
   "source": [
    "features = ['area', 'bedrooms', 'bathrooms', 'stories', 'parking']\n",
    "target = 'price'\n",
    "\n",
    "X = df[features].values\n",
    "y = df[target].values"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ea730a12",
   "metadata": {},
   "outputs": [],
   "source": [
    "scaler = StandardScaler()\n",
    "X = scaler.fit_transform(X)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "47c9f8a1",
   "metadata": {},
   "outputs": [],
   "source": [
    "num_clients = 5\n",
    "\n",
    "X_splits = np.array_split(X, num_clients)\n",
    "y_splits = np.array_split(y, num_clients)\n",
    "\n",
    "client_datasets = list(zip(X_splits, y_splits))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "28c03a04",
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_local_model(X, y, w, b, lr=0.01, epochs=20):\n",
    "    n = len(y)\n",
    "    for _ in range(epochs):\n",
    "        y_pred = X @ w + b\n",
    "        error = y_pred - y\n",
    "        dw = (1/n) * X.T @ error\n",
    "        db = (1/n) * np.sum(error)\n",
    "        w -= lr * dw\n",
    "        b -= lr * db\n",
    "    return w, b\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "e39e5154",
   "metadata": {},
   "outputs": [],
   "source": [
    "def fedavg(local_weights, local_biases, data_sizes):\n",
    "    total_samples = sum(data_sizes)\n",
    "    w_global = np.zeros_like(local_weights[0])\n",
    "    b_global = 0.0\n",
    "\n",
    "    for w, b, size in zip(local_weights, local_biases, data_sizes):\n",
    "        w_global += (size / total_samples) * w\n",
    "        b_global += (size / total_samples) * b\n",
    "\n",
    "    return w_global, b_global"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b422e2d0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Round 01 | Global MSE: 18614986305204.66\n",
      "Round 02 | Global MSE: 13393929796211.13\n",
      "Round 03 | Global MSE: 9793533084355.97\n",
      "Round 04 | Global MSE: 7303150641178.47\n",
      "Round 05 | Global MSE: 5575983506877.56\n",
      "Round 06 | Global MSE: 4375229822362.27\n",
      "Round 07 | Global MSE: 3538509584607.12\n",
      "Round 08 | Global MSE: 2954101115292.86\n",
      "Round 09 | Global MSE: 2544928372147.79\n",
      "Round 10 | Global MSE: 2257697238249.81\n",
      "Round 11 | Global MSE: 2055485978486.95\n",
      "Round 12 | Global MSE: 1912670773889.84\n",
      "Round 13 | Global MSE: 1811439266630.04\n",
      "Round 14 | Global MSE: 1739389068073.00\n",
      "Round 15 | Global MSE: 1687870202527.89\n",
      "Round 16 | Global MSE: 1650839084084.39\n",
      "Round 17 | Global MSE: 1624065007214.23\n",
      "Round 18 | Global MSE: 1604580001631.60\n",
      "Round 19 | Global MSE: 1590296948041.48\n",
      "Round 20 | Global MSE: 1579744177169.20\n",
      "Round 21 | Global MSE: 1571880799456.52\n",
      "Round 22 | Global MSE: 1565968045841.07\n",
      "Round 23 | Global MSE: 1561479509163.18\n",
      "Round 24 | Global MSE: 1558038430796.15\n",
      "Round 25 | Global MSE: 1555373810555.42\n"
     ]
    }
   ],
   "source": [
    "num_features = X.shape[1]\n",
    "w_global = np.zeros(num_features)\n",
    "b_global = 0.0\n",
    "\n",
    "rounds = 25\n",
    "\n",
    "for r in range(rounds):\n",
    "    local_weights = []\n",
    "    local_biases = []\n",
    "    data_sizes = []\n",
    "\n",
    "    for X_c, y_c in client_datasets:\n",
    "        w_local, b_local = train_local_model(\n",
    "            X_c, y_c,\n",
    "            w_global.copy(),\n",
    "            b_global\n",
    "        )\n",
    "\n",
    "        local_weights.append(w_local)\n",
    "        local_biases.append(b_local)\n",
    "        data_sizes.append(len(y_c))\n",
    "\n",
    "    w_global, b_global = fedavg(\n",
    "        local_weights, local_biases, data_sizes\n",
    "    )\n",
    "\n",
    "    \n",
    "    y_pred_global = X @ w_global + b_global\n",
    "    mse = mean_squared_error(y, y_pred_global)\n",
    "\n",
    "    print(f\"Round {r+1:02d} | Global MSE: {mse:.2f}\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
